export const SAVED_QUICKQUESTION = 'SAVED_QUICKQUESTION';
export const WORKSHEET_SAVER = 'WORKSHEET_SAVER';
export const WORKSHEET_DATA = 'WORKSHEET_DATA';
export const SAVE_USERNAME = 'SAVE_USERNAME';
export const ADD_QUESTION_TO_WORKSHEETDATA = 'ADD_QUESTION_TO_WORKSHEETDATA';
export const DELETE_QUESTION_TO_WORKSHEETDATA =
  'DELETE_QUESTION_TO_WORKSHEETDATA';
export const SAVED_QUESTIONARR = 'SAVED_QUESTIONARR';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
